config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :closets do
    get 'subcategories_for_category/:category_id', on: :collection, to: 'closets#subcategories_for_category'
    collection do
      post 'create/step', to: 'closets#create_step', as: 'create_step'
    end
  end

  post '/callback' => 'linebot#callback'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users/sign_up/:step', to: 'users/registrations#new', as: :new_user_registration_step
    post 'users/sign_up/:step', to: 'users/registrations#create'
    get 'users/cancel_account', to: 'users/registrations#cancel_account', as: :cancel_account_user
  end

  authenticated :user do
    root 'weather#index', as: :authenticated_root
  end

  root 'home#index'

  get 'home/index'
  get 'weather', to: 'weather#index', as: :weather
  get 'weather/show', to: 'weather#show', as: :show_weather
  get 'weather/map', to: 'weather#map', as: :map_weather
  get 'privacy_policy', to: 'static_pages#privacy_policy', as: :privacy_policy
  get 'terms_of_service', to: 'static_pages#terms_of_service', as: :terms_of_service
  post 'vision_api/upload', to: 'vision_api#upload'

  namespace :public do
    resources :contacts, only: %i[new create index] do
      collection do
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end
end

app/models/closet.rb
# frozen_string_literal: true

class Closet < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :subcategory, optional: true

  validates :name, presence: true
  validates :category_id, presence: true, numericality: { only_integer: true }
  validates :subcategory_id, presence: true, numericality: { only_integer: true }
  validates :last_displayed_at, presence: false

  def default_image
    ActionController::Base.helpers.asset_path('sample.png')
  end

  def image_url
    image.present? ? image.url : default_image
  end
end

app/controllers/closets_controller.rb
# frozen_string_literal: true

# ClosetsController handles the CRUD operations for the Closet model.
# It ensures that users can create, read, update, and delete their closet items.
class ClosetsController < ApplicationController
  before_action :set_closet, only: %i[show edit update destroy]
  before_action :set_categories_and_subcategories, only: %i[new edit create update]
  before_action :authenticate_user!
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  # GET /closets or /closets.json
  def index
    if user_signed_in?
      @user = current_user
      @closets = policy_scope(@user.closets)
    else
      redirect_to new_user_session_path, alert: I18n.t('alerts.login_required')
    end
  end

  # GET /closets/1 or /closets/1.json
  def show
    authorize @closet
  end

  # GET /closets/new
  def new
    @closet = Closet.new
    authorize @closet
  end

  # GET /closets/1/edit
  def edit
    authorize @closet
  end

  # POST /closets or /closets.json
  def create
    @closet = current_user.closets.new(closet_params)
    authorize @closet
    respond_to_create(@closet)
  end

  # PATCH/PUT /closets/1 or /closets/1.json
  def update
    authorize @closet
    if @closet.update(closet_update_params)
      redirect_to closet_url(@closet), notice: t('.success')
    else
      set_categories_and_subcategories
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /closets/1 or /closets/1.json
  def destroy
    authorize @closet
    @closet.destroy
    redirect_to closets_url, notice: t('.success')
  end

  def subcategories_for_category
    category_id = params[:category_id]
    @category = Category.find(category_id)
    authorize @category, :show?
    subcategories = Subcategory.where(category_id:)
    render json: subcategories
  end

  private

  def respond_to_create(closet)
    respond_to do |format|
      if closet.save
        format.html { redirect_to closet_url(closet), notice: t('.success') }
        format.json { render :show, status: :created, location: closet }
      else
        set_categories_and_subcategories
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: closet.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_closet
    @closet = Closet.find(params[:id])
  end

  def closet_params
    params.require(:closet).permit(:name, :category_id, :subcategory_id, :purchase_date, :size, :color,
                                   :purchase_location, :price, :usage_frequency, :season, :other_comments, :image)
  end

  def closet_update_params
    params.require(:closet).permit(:name, :category_id, :subcategory_id, :color, :season, :purchase_date, :size,
                                   :purchase_location, :price, :usage_frequency, :other_comments, :image)
  end

  def set_categories_and_subcategories
    @categories = Category.all
    @subcategories = Subcategory.all
  end
end

app/helpers/closets_helper.rb
# app/helpers/closets_helper.rb

module ClosetsHelper
  def display_clothes_photo(temperature, constitution_id, user)
    subcategory_ids = get_subcategory_ids(temperature, constitution_id)
    displayed_urls = []

    subcategory_ids.uniq.each do |subcategory_id|
      closet_item = find_appropriate_closet_item(user, subcategory_id)

      next if closet_item.nil?

      update_closet_item(closet_item)
      add_to_displayed_urls(displayed_urls, closet_item.image_url)
    end

    displayed_urls.compact
  end

  private

  def find_appropriate_closet_item(user, subcategory_id)
    user.closets
        .where(subcategory_id:)
        .where('last_displayed_at IS NULL OR last_displayed_at < ?', 24.hours.ago)
        .order('RANDOM()')
        .first ||
      user.closets
          .where(subcategory_id:)
          .order('RANDOM()')
          .first
  end

  def update_closet_item(closet_item)
    closet_item.update(last_worn_on: Time.zone.today, last_displayed_at: Time.zone.now)
  end

  def add_to_displayed_urls(displayed_urls, image_url)
    displayed_urls << image_url unless displayed_urls.include?(image_url)
  end
end

app/views/closets/_closet.html.erb
<div class="card" style="width: 18rem;">
  <%= image_tag closet.image.url, class: 'card-img-top', alt: closet.name, height: '250px'  %>
  <div class="card-body">
    <h5 class="card-title"><%= closet.name %></h5>
    <p class="card-text">
      <%= Category.find(closet.category_id).name %>/<%= Subcategory.find(closet.subcategory_id).name %>
    </p>
    <p class="card-text">
      <strong>季節:</strong>
      <%= closet.season %>
    </p>
    <%= link_to "詳細を見る", closet_path(closet), class: "btn btn-primary" %>
  </div>
</div>

app/views/closets/_form.html.erb
<%= form_with(model: @closet, class: 'row g-3') do |f| %>
  <% if @closet.errors.any? %>
    <div class="col-12">
      <div class="alert alert-danger">
        <h4 class="alert-heading"><%= pluralize(@closet.errors.count, "つのエラー") %> 登録できませんでした:</h4>
        <ul>
          <% @closet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <!-- Left Side -->
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :name, t('activerecord.attributes.closet.name'), class: 'form-label', for: 'closet_name' %>
        <%= f.text_field :name, class: 'form-control', id: 'closet_name' %>

        <%= f.label :image, t('activerecord.attributes.closet.image'), class: 'form-label' %>
        <%= f.file_field :image, id: 'image-upload', class: 'form-control' %>
        <% if f.object.image? %>
          <%= image_tag f.object.image.url, class: 'fashion_image mt-2', id: 'preview-image' %>
        <% else %>
          <%= image_tag 'sample.png', class: 'fashion_image mt-2', alt: 'default_icon', id: 'preview-image' %>
        <% end %>
      </div>

      <div class="mb-3">
        <%= f.label :category_id, t('activerecord.attributes.closet.category_id'), class: 'form-label' %>
        <%= f.collection_select :category_id, @categories, :id, :name, {}, { class: 'form-control', onchange: 'loadSubcategories(this.value)' } %>
      </div>

      <div class="mb-3">
        <%= f.label :subcategory_id, t('activerecord.attributes.closet.subcategory_id'), class: 'form-label' %>
        <%= f.collection_select :subcategory_id, @subcategories, :id, :name, {}, { class: 'form-control' } %>
      </div>
    </div>

    <!-- Right Side -->
    <div class="col-md-6">
      <div class="mb-3">
        <%= f.label :color, t('activerecord.attributes.closet.color'), class: 'form-label' %>
        <%= f.text_field :color, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :season, t('activerecord.attributes.closet.season'), class: 'form-label' %>
        <%= f.select :season, options_for_select(['春', '夏', '秋', '冬', 'その他'], selected: f.object.season), { include_blank: '' }, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :purchase_date, t('activerecord.attributes.closet.purchase_date'), class: 'form-label' %>
        <%= f.date_field :purchase_date, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :size, t('activerecord.attributes.closet.size'), class: 'form-label' %>
        <%= f.select :size, options_for_select(['子供服', 'XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'その他'], selected: f.object.size), { include_blank: '' }, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :purchase_location, t('activerecord.attributes.closet.purchase_location'), class: 'form-label' %>
        <%= f.text_field :purchase_location, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :price, t('activerecord.attributes.closet.price'), class: 'form-label' %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :usage_frequency, t('activerecord.attributes.closet.usage_frequency'), class: 'form-label' %>
        <%= f.select :usage_frequency, options_for_select([['高い', 5], ['やや高い', 4],['中', 3],['やや低い', 2], ['低い', 1]], selected: f.object.usage_frequency), { include_blank: '' }, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :other_comments, t('activerecord.attributes.closet.other_comments'), class: 'form-label' %>
        <%= f.text_area :other_comments, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="col-12 mt-3">
    <%= f.submit "更新する", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/closets/edit.html.erb
<h1><%= t('closets.edit_title', closetName: @closet.name) %></h1>

<%= render "form", closet: @closet %>

<br>

<div>
<%= link_to t('closets.show_link'), @closet %> |
<%= link_to t('closets.back_link'), closets_path %>
</div>

app/views/closets/index.html.erb
<div class="text-center">
  <h1><%= @user.name %>さんのクローゼット</h1>
  <%= link_to "新規アイテムの登録はこちら", new_closet_path, class: 'btn btn-primary btn-lg' %>
</div>
<br>
<div class="container">
  <div id="closets" class="row">
    <% @closets.each do |closet| %>
      <%= render closet %>
    <% end %>
  </div>
</div>

app/views/closets/new.html.erb
<div class="container-fluid light-blue-container p-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2 class="mb-4">クローゼットの登録</h2>

      <%= form_with(model: @closet, local: true, html: { multipart: true, class: 'needs-validation', novalidate: true }) do |f| %>
        <% if @closet.errors.any? %>
          <div class="alert alert-danger">
            <h4 class="alert-heading"><%= pluralize(@closet.errors.count, "つのエラー") %> 登録できませんでした:</h4>
            <ul>
              <% @closet.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <h3 class="mb-8">必須入力情報</h3>

        <div class="form-group">
          <%= f.label :image, t('activerecord.attributes.closet.image'), class: 'form-label' %>
          <%= f.file_field :image, id: 'image-upload', class: 'form-control' %>
          <% if f.object.image.present? %>
            <%= image_tag f.object.image.url, class: 'fashion_image mt-2', id: 'preview-image' %>
          <% else %>
            <%= image_tag 'sample.png', class: 'fashion_image mt-2', alt: 'default_icon', id: 'preview-image' %>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :name, t('activerecord.attributes.closet.name'), class: 'form-label', for: 'closet_name' %><span class="text-danger">*</span>
          <%= f.text_field :name, class: 'form-control', id: 'closet_name', placeholder: '' %>
        </div>

        <div class="mb-3">
          <%= f.label :category_id, t('activerecord.attributes.closet.category_id'), class: 'form-label' %><span class="text-danger">*</span>
          <%= f.collection_select :category_id, @categories, :id, :name, { prompt: '選択してください' }, { class: 'form-control', onchange: 'loadSubcategories(this.value)' } %>
        </div>

        <div class="mb-3">
          <%= f.label :subcategory_id, t('activerecord.attributes.closet.subcategory_id'), class: 'form-label' %><span class="text-danger">*</span>
          <%= f.collection_select :subcategory_id, [], :id, :name, {}, { class: 'form-control', disabled: true } %>
        </div></br>
        
        <div class="col-12 mt-3">
          <%= f.submit "登録する", class: 'btn btn-primary' %>
        </div></br>

        <h3 class="mb-8">任意入力</h3>

        <div class="form-group">
          <%= f.label :color, t('activerecord.attributes.closet.color'), class: 'form-label' %>
          <%= f.text_field :color, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :season, t('activerecord.attributes.closet.season'), class: 'form-label' %>
          <%= f.select :season, options_for_select(['春', '夏', '秋', '冬', 'その他'], selected: f.object.season), { include_blank: '' }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :purchase_date, t('activerecord.attributes.closet.purchase_date'), class: 'form-label' %>
          <%= f.date_field :purchase_date, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :size, t('activerecord.attributes.closet.size'), class: 'form-label' %>
          <%= f.select :size, options_for_select(['子供服', 'XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'その他'], selected: f.object.size), { include_blank: '' }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :purchase_location, t('activerecord.attributes.closet.purchase_location'), class: 'form-label' %>
          <%= f.text_field :purchase_location, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :price, t('activerecord.attributes.closet.price'), class: 'form-label' %>
          <%= f.text_field :price, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :usage_frequency, t('activerecord.attributes.closet.usage_frequency'), class: 'form-label' %>
          <%= f.select :usage_frequency, options_for_select([['高い', 5], ['やや高い', 4],['中', 3],['やや低い', 2], ['低い', 1]], selected: f.object.usage_frequency), { include_blank: '' }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :other_comments, t('activerecord.attributes.closet.other_comments'), class: 'form-label' %>
          <%= f.text_area :other_comments, class: 'form-control' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/closets/show.html.erb
<div class="container-fluid light-blue-container p-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2 class="mb-4">クローゼットの詳細</h2>
      
      <div class="row">
        <!-- Left Side -->
        <div class="col-md-6">
          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.name') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.name %></span>
          </div>

          <div class="field">
            <%= image_tag @closet.image.url, class: 'fashion_image', alt: @closet.name %>
          </div>

          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.category_id') %>:</strong>
            <span style="font-size: 30px;"><%= Category.find(@closet.category_id).name %>/<%= Subcategory.find(@closet.subcategory_id).name %></span>
          </div>

          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.season') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.season %></span>
          </div>
        </div>

        <!-- Right Side -->
        <div class="col-md-6">
          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.color') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.color %></span>
          </div>

          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.purchase_date') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.purchase_date %></span>
          </div>

          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.size') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.size %></span>
          </div>

          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.purchase_location') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.purchase_location %></span>
          </div>

          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.price') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.price %></span>
          </div>

          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.usage_frequency') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.usage_frequency %></span>
          </div>

          <div class="field">
            <strong style="font-size: 30px;"><%= t('activerecord.attributes.closet.other_comments') %>:</strong>
            <span style="font-size: 30px;"><%= @closet.other_comments %></span>
          </div>

          <div class="mt-3">
            <%= link_to t('closets.edit_link'), edit_closet_path(@closet), class: 'btn btn-warning me-2' %>
            <%= link_to t('closets.back_link'), closets_path, class: 'btn btn-secondary' %>
            <%= link_to t('closets.destroy_button'), @closet, method: :delete, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>