config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :closets do
    get 'subcategories_for_category/:category_id', on: :collection, to: 'closets#subcategories_for_category'
    collection do
      post 'create/step', to: 'closets#create_step', as: 'create_step'
    end
  end

  post '/callback' => 'linebot#callback'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users/sign_up/:step', to: 'users/registrations#new', as: :new_user_registration_step
    post 'users/sign_up/:step', to: 'users/registrations#create'
    get 'users/cancel_account', to: 'users/registrations#cancel_account', as: :cancel_account_user
  end

  authenticated :user do
    root 'weather#index', as: :authenticated_root
  end

  root 'home#index'

  get 'home/index'
  get 'weather', to: 'weather#index', as: :weather
  get 'weather/show', to: 'weather#show', as: :show_weather
  get 'weather/map', to: 'weather#map', as: :map_weather
  get 'privacy_policy', to: 'static_pages#privacy_policy', as: :privacy_policy
  get 'terms_of_service', to: 'static_pages#terms_of_service', as: :terms_of_service
  post 'vision_api/upload', to: 'vision_api#upload'

  namespace :public do
    resources :contacts, only: %i[new create index] do
      collection do
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="footer bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <p class="brand-name">Today_Fashion</p>
      </div>
      <div class="col-md-6 text-md-right">
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="/public/contacts/new">お問い合わせ</a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.kiyac.app/privacypolicy/SMicIccjd1pziE9F1Y3U">プライバシーポリシー</a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.kiyac.app/termsOfService/XTOStNuDNwqpQsbgxEEZ">サイト利用規約</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container-fluid">
          <!-- ナビゲーションバーのブランド。root_pathへのリンクと画像を含む -->
          <%= link_to root_path, class: 'navbar-brand' do %>
              <%= image_tag 'title.png', size: '200x40' %>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
              <% if user_signed_in? && current_user.image? %>
                  <%= image_tag current_user.image.url, class: 'icon_image' %>
              <% else %>
                  <%= image_tag 'default_image.png', class: 'icon_image', alt: 'Default Icon' %>
              <% end %>
          </button>  
          <!-- オフキャンバスのコンテンツ -->
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <% if user_signed_in? %>
                  <% if current_user.image? %>
                      <%= image_tag current_user.image.url, class: 'icon_image' %>
                  <% else %>
                      <%= image_tag 'default_image.png', class: 'icon_image', alt: 'Default Icon' %>
                  <% end %>
                  <span class="user-name"><%= current_user.name %></span>
              <% end %>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="閉じる"></button>
            </div>
              <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                      <%= link_to "トップページへ", root_path, class: "dropdown-item" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "プロフィール", edit_user_registration_path, class: 'dropdown-item' if user_signed_in? %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "マイ クローゼット", closets_path, class: "dropdown-item" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "全国の服装指数予報", map_weather_path, class: "dropdown-item" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to t('nav.log_out'), destroy_user_session_path, class: "dropdown-item", method: :delete if user_signed_in? %>
                    </li>
                    <li class="nav-item text-center mt-3">
                        <p class="mb-2">Line友達追加お願いいたします！</p>
                        <p class="mb-2">@079weaha</p>
                        <%= image_tag 'QRcode.png', class: 'img-fluid', alt: 'Line QR Code' %>
                    </li>
                  </ul>
              </div>
          </div>
      </div>
  </nav>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('devise_links.log_in'), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('devise_links.sign_up'), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t('devise_links.forgot_password'), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('devise_links.confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('devise_links.unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<% if devise_mapping.omniauthable? %>
  <% resource_class.omniauth_providers.each do |provider| %>
    <% if provider == :line %>
      <%= link_to omniauth_authorize_path(resource_name, provider), class: 'btn btn-outline-success btn-block', data: { turbo: false } do %>
        <i class="fab fa-line"></i> Lineでログイン
      <% end %>
    <% else %>
      <%= link_to omniauth_authorize_path(resource_name, provider), class: 'btn btn-outline-primary btn-block', data: { turbo: false } do %>
        <%= t('devise_links.sign_in_with', provider: OmniAuth::Utils.camelize(provider)) %>
      <% end %><br />
    <% end %>
  <% end %>
<% end %>