config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :closets do
    get 'subcategories_for_category/:category_id', on: :collection, to: 'closets#subcategories_for_category'
    collection do
      post 'create/step', to: 'closets#create_step', as: 'create_step'
    end
  end

  post '/callback' => 'linebot#callback'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users/sign_up/:step', to: 'users/registrations#new', as: :new_user_registration_step
    post 'users/sign_up/:step', to: 'users/registrations#create'
    get 'users/cancel_account', to: 'users/registrations#cancel_account', as: :cancel_account_user
  end

  authenticated :user do
    root 'weather#index', as: :authenticated_root
  end

  root 'home#index'

  get 'home/index'
  get 'weather', to: 'weather#index', as: :weather
  get 'weather/show', to: 'weather#show', as: :show_weather
  get 'weather/map', to: 'weather#map', as: :map_weather
  get 'privacy_policy', to: 'static_pages#privacy_policy', as: :privacy_policy
  get 'terms_of_service', to: 'static_pages#terms_of_service', as: :terms_of_service
  post 'vision_api/upload', to: 'vision_api#upload'

  namespace :public do
    resources :contacts, only: %i[new create index] do
      collection do
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end
end

app/controllers/weather_controller.rb
# frozen_string_literal: true

# WeatherController manages weather-related actions and views.
class WeatherController < ApplicationController
  include WeatherHelper

  before_action :validate_city, only: [:show]
  before_action :load_prefecture_data, only: [:index]
  before_action :authenticate_user!
  after_action :verify_authorized, except: %i[index show]
  after_action :verify_policy_scoped, only: :index

  def index
    skip_policy_scope

    weather_data = fetch_weather_data_for_user(current_user)
    @weather_data = weather_data[:default_city]
    @second_weather_data = weather_data[:second_city]

    flash[:alert] = I18n.t('weather.fetch_failed') unless @weather_data || @second_weather_data
  end

  def show
    @weather_data = fetch_weather_service_data(params[:city] || default_city)

    if @weather_data
      process_weather_data(@weather_data, params[:city] || default_city)
    else
      flash[:alert] = I18n.t('weather.fetch_failed')
      redirect_to action: :index
    end
  end

  def map
    authorize :weather, :map?
    @weather_data = fetch_weather_for_prefectures
    flash_part_weather_fetch_warning if weather_fetch_failed?
  end

  private

  def validate_city
    redirect_to(action: :index, alert: I18n.t('weather.enter_city')) if params[:city].blank?
  end

  def load_prefecture_data
    csv_path = Rails.root.join('prefectures.csv')
    @prefecture_data = CSV.read(csv_path, headers: true).map { |row| [row['prefecture'], row['english']] }
  end

  def fetch_weather_data_for_user(user)
    default_city = fetch_city_name(user&.prefecture_id, 'Tokyo')
    second_city = fetch_city_name(user&.second_prefecture_id, 'Osaka')

    { default_city: fetch_weather_api_data(default_city), second_city: fetch_weather_api_data(second_city) }
  end

  def fetch_city_name(prefecture_id, default_city)
    prefecture_id.present? ? Prefecture.find(prefecture_id).name : default_city
  end

  def flash_weather_fetch_warning
    flash.now[:alert] = I18n.t('weather.fetch_failed')
  end

  def fetch_weather_service_data(city)
    response = WeatherService.new(city).fetch_weather
    response.success? ? response.parsed_response : nil
  end

  def fetch_weather_api_data(city_name)
    api_key = Rails.application.credentials.dig(:openweathermap, :api_key)
    response = HTTParty.get('https://api.openweathermap.org/data/2.5/forecast',
                            query: { q: city_name, appid: api_key, units: 'metric', lang: 'ja' })
    return response.parsed_response if response.success?

    nil
  end

  def process_weather_data(weather_data, city)
    rainfall = fetch_rainfall(weather_data)
    @weather = build_weather_data(weather_data, rainfall)
    fetch_and_update_weather_forecast(city)
    send_rainfall_notification(rainfall) if rainfall.positive?
  end

  def fetch_and_update_weather_forecast(city)
    response_forecast = WeatherService.new(city).fetch_weather_forecast
    @weather_data = response_forecast.parsed_response if response_forecast.success?
  end

  def fetch_rainfall(weather_data)
    weather_data.dig('rain', '1h') || weather_data.dig('rain', '3h') || 0
  end

  def send_rainfall_notification(rainfall)
    send_line_notification(I18n.t('weather.rainfall_alert', city: @weather[:name])) if rainfall.positive?
  end

  def fetch_weather_for_prefectures
    prefecture_ids = [1, 4, 13, 23, 15, 26, 34, 39, 40, 46, 47]
    Prefecture.where(id: prefecture_ids).map do |prefecture|
      fetch_prefecture_weather(prefecture)
    end
  end

  def fetch_prefecture_weather(prefecture)
    weather = fetch_weather_api_data(prefecture.name)
    forecasts = select_forecasts(weather)
    { name: prefecture.name, weather:, forecasts: }
  end

  def select_forecasts(weather)
    return [] unless weather.present? && weather['list'].present?

    weather['list'].select do |forecast|
      forecast_within_24_hours?(forecast['dt'])
    end
  end

  def forecast_within_24_hours?(timestamp)
    Time.zone.at(timestamp) <= 24.hours.from_now
  end

  def weather_fetch_failed?
    @weather_data.any? { |data| data[:weather].nil? }
  end

  def flash_part_weather_fetch_warning
    flash.now[:alert] = I18n.t('weather.partial_fetch_failed')
  end
end

app/helpers/weather_helper.rb
# app/helpers/weather_helper.rb

module WeatherHelper
  def build_weather_data(weather_data, rainfall)
    {
      name: extract_weather_name(weather_data),
      temp_celsius: extract_temperature(weather_data, 'temp'),
      temp_min_celsius: extract_temperature(weather_data, 'temp_min'),
      temp_max_celsius: extract_temperature(weather_data, 'temp_max'),
      humidity: extract_humidity(weather_data),
      wind_speed: extract_wind_speed(weather_data),
      description: extract_description(weather_data),
      rainfall:
    }
  end

  def extract_weather_name(weather_data)
    weather_data['name']
  end

  def extract_temperature(weather_data, key)
    kelvin_to_celsius(weather_data['main'][key]).round(1)
  end

  def extract_humidity(weather_data)
    weather_data['main']['humidity']
  end

  def extract_wind_speed(weather_data)
    weather_data['wind']['speed']
  end

  def extract_description(weather_data)
    weather_data['weather'][0]['description']
  end

  def kelvin_to_celsius(kelvin)
    kelvin - 273.15
  end
end

app/views/weather/_weather_card.html.erb
<% if weather_data.present? && weather_data['city'].present? %>
  <div class="card mt-3">
    <div class="card-body">
      <h5 class="card-title"><%= weather_data['city']['name'] %></h5>
      <div class="row">
        <div class="col">
          <p>天気: <%= weather_data['list'][0]['weather'][0]['description'] %></p>
          <img src="https://openweathermap.org/img/wn/<%= weather_data['list'][0]['weather'][0]['icon'] %>@2x.png" alt="Weather Icon">
          <% if weather_data['list'][0]['rain'] && weather_data['list'][0]['rain']['1h'] %>
            <p>降水量: <%= weather_data['list'][0]['rain']['1h'] %> mm</p>
          <% end %>
          <p>湿度: <%= weather_data['list'][0]['main']['humidity'] %> %</p>
          <p>風速: <%= weather_data['list'][0]['wind']['speed'] %> m/s</p>
        </div>
        <div class="col ml-auto">
          <p>今日のおすすめファッション</p>
          <div style='display: flex; flex-wrap: wrap;'>
            <%= dress_code_suggestion(
              weather_data['list'][0]['main']['temp_max'],
              current_user&.constitution_id.to_i
            ) %>
          </div></br>
          <div style='display: flex; flex-wrap: wrap;'>
            <% if current_user %>
              <% image_urls = display_clothes_photo(weather_data['list'][0]['main']['temp_max'], current_user.constitution_id.to_i, current_user) %>
              <% image_urls.each do |image_url| %>
                <%= image_tag image_url, alt: "Clothes Photo", size: '50x50' %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col ml-auto">
          <p>明日のおすすめファッション</p>
          <div style='display: flex; flex-wrap: wrap;'>
            <%= dress_code_suggestion(
              weather_data['list'][8]['main']['temp_max'],
              current_user&.constitution_id.to_i
            ) %>
          </div></br>
          <div style='display: flex; flex-wrap: wrap;'>
            <% if current_user %>
              <% image_urls = display_clothes_photo(weather_data['list'][8]['main']['temp_max'], current_user.constitution_id.to_i, current_user) %>
              <% image_urls.each do |image_url| %>
                <%= image_tag image_url, alt: "Clothes Photo", size: '50x50' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div></br>
      <div class="row">
        <% current_time = Time.now %>
        <% forecasts = weather_data['list'].select { |forecast| Time.at(forecast['dt']) <= current_time + 24.hours } %>
        <div class="row flex-nowrap overflow-auto">
          <% forecasts.each do |forecast| %>
            <div class="col-md-2 mb-3" style="flex: 0 0 auto;">
              <div class="card">
                <div class="card-body p-1">
                  <h6 class="card-subtitle mb-1 text-muted" style="font-size: 0.8rem;"><%= Time.at(forecast['dt']).strftime('%H:%M') %></h6>
                  <div style='display: flex; flex-wrap: wrap;'>
                    <img src="https://openweathermap.org/img/wn/<%= forecast['weather'][0]['icon'] %>@2x.png" alt="Weather Icon" class="img-fluid" style="width: 100px; height: 100px;">
                    <%= get_clothing_icons(forecast['main']['temp'], current_user.constitution_id).join(' ').html_safe %>
                  </div>
                  <% if forecast['rain'].present? && forecast['rain']['3h'].present? %>
                    <p class="card-text mb-1" style="font-size: 0.7rem;">降水量: <%= forecast['rain']['3h'] %>mm</p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <p>天気情報がありません。</p>
<% end %>

app/views/weather/index.html.erb
<% if @weather_data.present? %>
  <div class="container">
    <%= render partial: 'weather_card', locals: { weather_data: @weather_data } %>
  </div>
<% else %>
  <p>天気情報がありません。</p>
<% end %>

<% if @second_weather_data.present? %>
  <div class="container mt-5">
    <%= render partial: 'weather_card', locals: { weather_data: @second_weather_data } %>
  </div>
<% else %>
  <p>天気情報がありません。</p>
<% end %>

<div class="container">
  <%= clothing_index(current_user.constitution_id).join(' ').html_safe %>
</div>

app/views/weather/map.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Japan Map Example</title>
  <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
</head>
<body id="map-page">

<div class="left-column">
  <div class="container">
    <div class="row">
      <% @weather_data.each do |data| %>
        <div class="col-md-6 mb-2">
          <div class="card">
            <div class="card-header py-1">
              <h6 class="card-title mb-0" style="font-size: 0.9rem;"><%= data[:name] %></h6> 
            </div>
            <div class="card-body p-2"> 
              <% if data[:weather] && data[:weather]['list'] %>
                <% current_time = Time.now %>
                <% forecasts = data[:weather]['list'].select { |forecast| Time.at(forecast['dt']) <= current_time + 24.hours } %>
                <div class="row flex-nowrap overflow-auto">
                  <% forecasts.each do |forecast| %>
                    <div class="col-md-3 mb-3" style="flex: 0 0 auto;">
                      <div class="card">
                        <div class="card-body p-1"> 
                          <h6 class="card-subtitle mb-1 text-muted" style="font-size: 0.8rem;"><%= Time.at(forecast['dt']).strftime('%H:%M') %></h6>
                          <div style='display: flex; flex-wrap: wrap;'>
                            <img src="https://openweathermap.org/img/wn/<%= forecast['weather'][0]['icon'] %>@2x.png" alt="Weather Icon" class="img-fluid" style="width: 50px; height: 50px;">
                            <%= get_clothing_icons(forecast['main']['temp'], current_user.constitution_id).join(' ').html_safe %>
                          </div>
                          <% if forecast['rain'].present? && forecast['rain']['3h'].present? %>
                            <p class="card-text mb-1" style="font-size: 0.7rem;">降水量: <%= forecast['rain']['3h'] %>mm</p> 
                          <% end %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% else %>
                <p>天気情報が取得できませんでした。</p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="right-column">
  <div id="map-container" data-show-weather-path="<%= show_weather_path %>"></div>
  <p id="text"></p>
  <div style='display: flex; flex-wrap: wrap;'>
    <%= clothing_index(current_user.constitution_id).join(' ').html_safe %>
  </div>
</div>

</body>
</html>

app/views/weather/show.html.erb
<div class="container mt-5">
  <h1><%= @weather[:name] %> の天気と服装指数予報</h1>

  <div class="mt-4">
    <% if @weather_data.present? %>
      <div class="row">
        <% @weather_data['list'].group_by { |forecast| Time.at(forecast['dt']).strftime('%Y-%m-%d') }.each do |date, forecasts| %>
          <div class="col-12 mb-3">
            <div class="card">
              <div class="card-header">
                <strong><%= date %></strong>
              </div>
              <div class="card-body">
                <div class="row">
                  <% forecasts.each do |forecast| %>
                    <div class="col-md-3 mb-1">
                      <div class="card">
                        <div class="card-body p-3">
                          <h6 class="card-subtitle mb-2 text-muted"><%= Time.at(forecast['dt']).strftime('%H:%M') %></h6>
                          <img src="https://openweathermap.org/img/wn/<%= forecast['weather'][0]['icon'] %>@2x.png" alt="Weather Icon" class="img-fluid">
                          <% if forecast['rain'].present? && forecast['rain']['3h'].present? %>
                            <p class="card-text mb-1">降水量: <%= forecast['rain']['3h'] %>mm</p>
                          <% end %>
                          <div style='display: flex; flex-wrap: wrap;'>
                            <p style="font-size: 0.7rem;">服装指数:</p>
                            <%= get_clothing_icons(forecast['main']['temp'], current_user.constitution_id).join(' ').html_safe %>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  <p style="font-size: 0.7rem;">おすすめファッション</p>
                  <div style='display: flex; flex-wrap: wrap;'>
                    <% first_forecast = forecasts.first %>
                    <%= dress_code_suggestion(first_forecast['main']['temp'], current_user&.constitution_id.to_i) %>
                    <h1> | </h1>
                    <% if current_user %>
                      <% image_urls = display_clothes_photo(first_forecast['main']['temp'], current_user.constitution_id.to_i, current_user) %>
                      <% image_urls.each do |image_url| %>
                        <%= image_tag image_url, alt: "Clothes Photo", size: '50x50' %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="mt-4">天気情報が取得できませんでした。</p>
    <% end %>
  </div>
  <%= clothing_index(current_user.constitution_id).join(' ').html_safe %>
  <div class="mt-4">
    <%= link_to '戻る', weather_path, class: "btn btn-primary" %>
  </div>
</div>